# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "622cb6968388d863a288709e40e7def3"
name = "test-application-run"
application_url = "https://helping-vid-fr-immediately.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "themedemo201.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://helping-vid-fr-immediately.trycloudflare.com/auth/callback",
  "https://helping-vid-fr-immediately.trycloudflare.com/auth/shopify/callback",
  "https://helping-vid-fr-immediately.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
